name: Lint

on:
  push:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: read

jobs:
  super-linter:
    uses: harryzcy/github-actions/.github/workflows/linter.yml@main

  go-lint:
    uses: harryzcy/github-actions/.github/workflows/golangci-lint.yml@main
