name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  update_release_draft:
    name: Release Drafter
    uses: harryzcy/github-actions/.github/workflows/release-drafter.yml@main
