name: Tests

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v*"
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  go-test:
    name: Go Tests
    permissions:
      contents: read
      id-token: write
    uses: harryzcy/github-actions/.github/workflows/go.yml@main
    with:
      latest: 1
