name: Tests

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v*"
  pull_request:
    branches:
      - main

jobs:
  go-test:
    name: Go Tests
    uses: harryzcy/github-actions/.github/workflows/go.yml@main
    with:
      latest: 1
